apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler

metadata:
  name: parser-hpa
  namespace: ingest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: parser
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
