version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - v_grafana_data:/var/lib/grafana
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data-ingestion-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-lifecycle
    networks:
      - data-ingestion-network

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    user: root
    ports:
      - "9095:9095"
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ../monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - v_loki_data:/loki
    networks:
      - data-ingestion-network

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ../monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - data-ingestion-network

volumes:
  v_loki_data:
  v_grafana_data:
